<a href="https://colab.research.google.com/github/shrutiiiyadav/-_-1-IRIS-FLOWER-CLASSIFICATION/blob/main/Copy_of_TSF_EXP_2_(ROLL_NO_20).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**NAME:** Shruti Yadav



**ROLL NO:**20



**Experiment No.2: **   Implementation of Pre-processing Techniques.

**Minimum Marks:** 10


**Experimentation:**
1. Understand the different preprocessing techniques with time series data.
2. Explore various techniques for handling missing values, outliers, scaling, and
trend removal.
3. Apply these techniques to a real-world dataset with various preprocessing
challenges

**How to Import Data**

In [ ]:
import pandas as pd
raw_csv_data = pd.read_csv('/content/Index2018.csv')
df_comp = raw_csv_data.copy()

**How to Explore the Data**

In [ ]:
import pandas as pd
df_comp.date.describe()

count           6269
unique          6269
top       07/01/1994
freq               1
Name: date, dtype: object

**How to Transform Strings into Dates**

In [ ]:
df_comp.date.head()

0    07/01/1994
1    10/01/1994
2    11/01/1994
3    12/01/1994
4    13/01/1994
Name: date, dtype: object

**How to Transform Numbers into Dates**

In [ ]:
pd.to_datetime(df_comp.date, format="%d/%m/%Y")

0      1994-01-07
1      1994-01-10
2      1994-01-11
3      1994-01-12
4      1994-01-13
          ...
6264   2018-01-23
6265   2018-01-24
6266   2018-01-25
6267   2018-01-26
6268   2018-01-29
Name: date, Length: 6269, dtype: datetime64[ns]

In [ ]:
df_comp["date"] = pd.to_datetime(df_comp.date, format="%d/%m/%Y")
df_comp.head()

        date     spx      dax     ftse    nikkei
0 1994-01-07  469.90  2224.95  3445.98  18124.01
1 1994-01-10  475.27  2225.00  3440.58  18443.44
2 1994-01-11  474.13  2228.10  3413.77  18485.25
3 1994-01-12  474.17  2182.06  3372.02  18793.88
4 1994-01-13  472.47  2142.37  3360.01  18577.26

In [ ]:
pd.to_datetime(df_comp.date)

0      1994-01-07
1      1994-01-10
2      1994-01-11
3      1994-01-12
4      1994-01-13
          ...
6264   2018-01-23
6265   2018-01-24
6266   2018-01-25
6267   2018-01-26
6268   2018-01-29
Name: date, Length: 6269, dtype: datetime64[ns]

In [ ]:
pd.to_datetime(df_comp.date, dayfirst=True)

0      1994-01-07
1      1994-01-10
2      1994-01-11
3      1994-01-12
4      1994-01-13
          ...
6264   2018-01-23
6265   2018-01-24
6266   2018-01-25
6267   2018-01-26
6268   2018-01-29
Name: date, Length: 6269, dtype: datetime64[ns]

In [ ]:
df_comp.date = pd.to_datetime(df_comp.date, dayfirst=True)

In [ ]:
df_comp.head()

        date     spx      dax     ftse    nikkei
0 1994-01-07  469.90  2224.95  3445.98  18124.01
1 1994-01-10  475.27  2225.00  3440.58  18443.44
2 1994-01-11  474.13  2228.10  3413.77  18485.25
3 1994-01-12  474.17  2182.06  3372.02  18793.88
4 1994-01-13  472.47  2142.37  3360.01  18577.26

In [ ]:
df_comp.date.describe()

count                             6269
mean     2006-01-14 19:36:59.492742144
min                1994-01-07 00:00:00
25%                2000-01-11 00:00:00
50%                2006-01-12 00:00:00
75%                2012-01-19 00:00:00
max                2018-01-29 00:00:00
Name: date, dtype: object

**How To Use set_index()**

In [ ]:
help(df_comp.set_index)

Help on method set_index in module pandas.core.frame:

set_index(keys, *, drop: 'bool' = True, append: 'bool' = False, inplace: 'bool' = False, verify_integrity: 'bool' = False) -> 'DataFrame | None' method of pandas.core.frame.DataFrame instance
    Set the DataFrame index using existing columns.

    Set the DataFrame index (row labels) using one or more existing
    columns or arrays (of the correct length). The index can replace the
    existing index or expand on it.

    Parameters
    ----------
    keys : label or array-like or list of labels/arrays
        This parameter can be either a single column key, a single array of
        the same length as the calling DataFrame, or a list containing an
        arbitrary combination of column keys and arrays. Here, "array"
        encompasses :class:`Series`, :class:`Index`, ``np.ndarray``, and
        instances of :class:`~collections.abc.Iterator`.
    drop : bool, default True
        Delete columns to be used as the new index.
    append : bool, default False
        Whether to append columns to existing index.
    inplace : bool, default False
        Whether to modify the DataFrame rather than creating a new one.
    verify_integrity : bool, default False
        Check the new index for duplicates. Otherwise defer the check until
        necessary. Setting to False will improve the performance of this
        method.

    Returns
    -------
    DataFrame or None
        Changed row labels or None if ``inplace=True``.

    See Also
    --------
    DataFrame.reset_index : Opposite of set_index.
    DataFrame.reindex : Change to new indices or expand indices.
    DataFrame.reindex_like : Change to same indices as other DataFrame.

    Examples
    --------
    >>> df = pd.DataFrame({'month': [1, 4, 7, 10],
    ...                    'year': [2012, 2014, 2013, 2014],
    ...                    'sale': [55, 40, 84, 31]})
    >>> df
       month  year  sale
    0      1  2012    55
    1      4  2014    40
    2      7  2013    84
    3     10  2014    31

    Set the index to become the 'month' column:

    >>> df.set_index('month')
           year  sale
    month
    1      2012    55
    4      2014    40
    7      2013    84
    10     2014    31

    Create a MultiIndex using columns 'year' and 'month':

    >>> df.set_index(['year', 'month'])
                sale
    year  month
    2012  1     55
    2014  4     40
    2013  7     84
    2014  10    31

    Create a MultiIndex using an Index and a column:

    >>> df.set_index([pd.Index([1, 2, 3, 4]), 'year'])
             month  sale
       year
    1  2012  1      55
    2  2014  4      40
    3  2013  7      84
    4  2014  10     31

    Create a MultiIndex using two Series:

    >>> s = pd.Series([1, 2, 3, 4])
    >>> df.set_index([s, s**2])
          month  year  sale
    1 1       1  2012    55
    2 4       4  2014    40
    3 9       7  2013    84
    4 16     10  2014    31

In [ ]:
df_comp.head()

        date     spx      dax     ftse    nikkei
0 1994-01-07  469.90  2224.95  3445.98  18124.01
1 1994-01-10  475.27  2225.00  3440.58  18443.44
2 1994-01-11  474.13  2228.10  3413.77  18485.25
3 1994-01-12  474.17  2182.06  3372.02  18793.88
4 1994-01-13  472.47  2142.37  3360.01  18577.26

In [ ]:
df_comp.set_index("date")

                    spx       dax         ftse    nikkei
date
1994-01-07   469.900000   2224.95  3445.980000  18124.01
1994-01-10   475.270000   2225.00  3440.580000  18443.44
1994-01-11   474.130000   2228.10  3413.770000  18485.25
1994-01-12   474.170000   2182.06  3372.020000  18793.88
1994-01-13   472.470000   2142.37  3360.010000  18577.26
...                 ...       ...          ...       ...
2018-01-23  2839.130362  13559.60  7731.827774  24124.15
2018-01-24  2837.544008  13414.74  7643.428966  23940.78
2018-01-25  2839.253031  13298.36  7615.839954  23669.49
2018-01-26  2872.867839  13340.17  7665.541292  23631.88
2018-01-29  2853.528411  13324.48  7671.533300  23629.34

[6269 rows x 4 columns]

**How to use as_freq()**

In [ ]:
df_comp.asfreq('d')

           date  spx  dax  ftse  nikkei
1970-01-01  NaT  NaN  NaN   NaN     NaN

In [ ]:
df_comp.asfreq('a')

Empty DataFrame
Columns: [date, spx, dax, ftse, nikkei]
Index: []

In [ ]:
df_comp=df_comp.asfreq(freq='d')

In [ ]:
df_comp

           date  spx  dax  ftse  nikkei
1970-01-01  NaT  NaN  NaN   NaN     NaN

In [ ]:
df_comp=df_comp.asfreq(freq='b')

In [ ]:
df_comp.head()

           date  spx  dax  ftse  nikkei
1970-01-01  NaT  NaN  NaN   NaN     NaN

**How to Find Missing Values**

In [ ]:
df_comp.isna()

            date   spx   dax  ftse  nikkei
1970-01-01  True  True  True  True    True

In [ ]:
df_comp.isna().sum()

date      1
spx       1
dax       1
ftse      1
nikkei    1
dtype: int64

**How to Fill Missing Values**

In [ ]:
df_comp.spx = df_comp.spx.fillna(method="ffill")

In [ ]:
df_comp.ftse = df_comp.ftse.fillna(method='bfill')

In [ ]:
df_comp.dax = df_comp.dax.fillna(value=df_comp.dax.mean())